#!/usr/bin/python3

# Python Third-Party Modules
#
#  - mqtt:
#      - https://pypi.org/project/paho-mqtt
#      - python3-paho-mqtt, pip install paho-mqtt
#  - influx:
#      - https://pypi.org/project/influxdb
#      - python3-influxdb, pip install influxdb
#  - docker:
#      - https://docker-py.readthedocs.io
#      - python3-docker, pip install docker
#  - requests:
#      - https://requests.readthedocs.io
#      - python3-requests, pip install requests
#
# Docker Compose V2 - https://docs.docker.com/compose/migrate/
#
#      'docker compose version'
#      Docker Compose version v2.*
#
# Gluetun VPN client - https://github.com/qdm12/gluetun

import argparse
import glob
import json
import logging
import logging.handlers
import os
import random
import re
import socket
import subprocess
import sys
import threading
import time
from datetime import datetime, timezone

import docker
import paho.mqtt.client as mqtt_client
import pymysql
import requests
import yaml
from influxdb import InfluxDBClient
from influxdb.exceptions import InfluxDBClientError
from requests import ConnectionError

parser = argparse.ArgumentParser()
parser.add_argument(
    "--config", metavar="-c", required=True, type=str, help="config file"
)
args = parser.parse_args()

config = yaml.safe_load(open(args.config))

debug = config["debug"]

instance_name = config["instance_name"]

if config["is_docker_container_multi"]:
    hostname_fqdn = socket.gethostname()
else:
    hostname_fqdn = config["hostname_fqdn"]

gluetun_proxy_port = config["gluetun_proxy_port"]

shuffle_vpn_provider = config["shuffle_vpn_provider"]

mysql_enable = config["mysql_enable"]

mqtt_enable = config["mqtt_enable"]
mqtt_broker = config["mqtt_broker"]
mqtt_topic_pub = config["mqtt_topic_pub"] + instance_name
mqtt_topic_sub = config["mqtt_topic_sub"]

ttime_mqtt_pub = config["ttime_mqtt_pub"]
ttime_loop_sleep = ttime_mqtt_pub - 60

influxdb_enable = config["influxdb_enable"]
influxdb_host = config["influxdb_host"]
influxdb_port = config["influxdb_port"]
influxdb_user = config["influxdb_user"]
influxdb_password = config["influxdb_password"]
influxdb_database = config["influxdb_database"]
influxdb_measurement = config["influxdb_measurement"]

container_name = config["container_name"]
gluetun_healthcheck_port = config["gluetun_healthcheck_port"]
gluetun_control_port = config["gluetun_control_port"]

if config["is_docker_container"]:
    gluetun_path = "/app/gluetun"
else:
    gluetun_path = config["gluetun_path"]

gluetun_servers_json = os.path.join(gluetun_path, "gluetun_config", "servers.json")

start_delay = config["start_delay"]

ttl_min = config["ttl_min"]
ttl_max = config["ttl_max"]
ttl_min_debug = config["ttl_min_debug"]
ttl_max_debug = config["ttl_max_debug"]

checkup_and_pub_interval = ttime_mqtt_pub

#
# Docker
#
compose_file_path = os.path.join(gluetun_path, "docker-compose.yml")
client = docker.from_env()
#
# Logging (and debugging)
#
# todo: allow logging to one or both of syslog/stdout
# https://www.delftstack.com/howto/python/python-logging-to-file-and-console/
# handler = [logging.handlers.SysLogHandler(address='/dev/log'), logging.StreamHandler(sys.stdout)]
#
logger = logging.getLogger("randomizer")

level = logging.DEBUG if debug else logging.INFO
logger.setLevel(level)

if config["is_docker_container"]:
    handler = logging.StreamHandler(sys.stdout)
    formatter = logging.Formatter(
        "%(asctime)s %(name)s %(levelname)-8s %(message)s", datefmt="%Y-%m-%d %H:%M:%S"
    )
else:
    handler = logging.handlers.SysLogHandler(address="/dev/log")
    formatter = logging.Formatter(
        "%(name)s %(levelname)-8s %(message)s", datefmt="%Y-%m-%d %H:%M:%S"
    )

handler.setFormatter(formatter)
logger.addHandler(handler)


def send_request(method=None, url=None, data=None, headers=None, proxy=None):
    #
    # https://stackoverflow.com/questions/44448625/how-to-handle-a-connection-error-gracefully-in-requests
    #
    r = None
    connection_timeout = 5
    start_time = time.time()

    proxies = (
        {
            "http": proxy,
            "https": proxy,
        }
        if proxy
        else None
    )

    while True:
        try:
            if method == "get":
                r = requests.get(url, proxies=proxies)
            if method == "put":
                r = requests.put(url, data=data, headers=headers, proxies=proxies)
            break
        except ConnectionError as e:
            if time.time() > start_time + connection_timeout:
                logger.debug(f"All request attempts have failed.")
                logger.debug(f"{e}")
                response = "NOTOK"
                break
            else:
                logger.debug(f"Request timed out. Trying again.")
                time.sleep(1)
    if r and r.status_code == 200:
        if "application/json" in r.headers.get("Content-Type", ""):
            json_response = r.json()
            response = (
                json_response.get("ip")
                or json_response.get("ip_address")
                or json_response.get("ip_addr")
            )
        else:
            response = "OK"
    else:
        response = "NOTOK"

    return response


def influxdb_pub(vpn_gw_name, ipaddr_public):
    logger.info(f"Publishing details to influxdb...")
    time_now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    # ttime_now = time.time()
    d = {}
    d["measurement"] = influxdb_measurement
    d["time"] = time_now
    d["tags"] = {"vpn_tracker": "vpn_tracker"}
    vpn_provider = vpn().get_provider_name()
    d["fields"] = {
        "hostname": instance_name,
        "vpn_provider": vpn_provider,
        "gateway": vpn_gw_name,
        "ipaddr_public": ipaddr_public,
    }
    try:
        InfluxDBClient(
            influxdb_host,
            influxdb_port,
            influxdb_user,
            influxdb_password,
            influxdb_database,
            ssl=True,
            verify_ssl=True,
        ).write_points([d])
    # except:
    except InfluxDBClientError as e:
        logger.info(f"Publishing details to influxdb failed but continuing...")
        logger.debug(f"error: {e}")
        pass


class Docker:
    def __init__(self):
        pass

    def docker_get_ready_state(self):
        # Checking for valid ip is an additional state on top of passing healthcheck
        i = 15
        while i >= 1:
            my_ipaddr = vpn().get_public_ip()
            try:
                socket.inet_aton(my_ipaddr)
                return True
            except socket.error as e:
                logger.info(f"Waiting for valid ip address...")
                logger.debug(f"error: {e}")
                time.sleep(1)
                i -= 1
        return False

    def docker_container_start(self):
        if not os.path.exists(compose_file_path):
            logger.info(f"No Docker compose file ({compose_file_path}). Exiting.")
            os._exit(1)

        logger.info("Starting docker container...")

        for attempt in range(3):
            try:
                subprocess.run(
                    [
                        "docker",
                        "compose",
                        "-f",
                        compose_file_path,
                        "up",
                        "-d",
                        "--force-recreate",
                    ],
                    check=True,
                )

                # wait up to ~30 seconds for healthy state
                for _ in range(6):
                    if self.docker_checkup():
                        logger.info("Containers started successfully.")
                        return True
                    time.sleep(5)

            except subprocess.CalledProcessError as e:
                logger.warning(f"Attempt {attempt+1} failed: {e}")

            logger.info("Retrying container start...")
            time.sleep(5)

        logger.error("Failed to start containers after retries.")
        return False

    def docker_container_start_old(self):
        if not os.path.exists(compose_file_path):
            logger.info(f"No Docker compose file ({compose_file_path}). Exiting.")
            os._exit(1)
        logger.info(f"Starting docker container...")
        try:
            subprocess.call(["docker", "compose", "-f", compose_file_path, "up", "-d"])
            time.sleep(5)
        except ValueError as e:
            logger.debug(f"{e}")
            logger.info(f"Start of docker container failed.")
            return False

    def docker_container_get(self):
        connection_timeout = 5
        start_time = time.time()
        while True:
            try:
                container = client.containers.get(container_name)
                break
            except docker.errors.NotFound:
                if time.time() > start_time + connection_timeout:
                    logger.info(f"Unable to get docker container details.")
                    os._exit(1)
                else:
                    self.docker_container_start()
                    time.sleep(1)
        if container:
            return container
        else:
            logger.info(f"Unable to get docker container details.")
            os._exit(1)

    def docker_checkup(self):
        if vpn().get_healthcheck() == "OK":
            logger.info(f"Healthcheck has passed. Continuing...")
            return True

        try:
            container = self.docker_container_get()

            running = container.attrs["State"]["Running"]
            healthy = container.attrs["State"]["Health"]["Status"]

            logger.debug(f"container_state_running: {running}")
            logger.debug(f"container_state_healthy: {healthy}")

            if running and healthy == "healthy":
                logger.info(f"Container is running and healthy.")
                return True

            logger.info(f"Container not ready (running={running}, health={healthy})")
            return False

        except Exception as e:
            logger.debug(f"{e}")
            return False

    def docker_checkup_old(self):
        # If a healthcheck passes, we can just quickly return True. A healthcheck indicates
        # all supporting mechanisms are functioning as needed.
        if vpn().get_healthcheck() == "OK":
            logger.info(f"Healthcheck has passed. Continuing...")
            return True
        else:
            cstate = False

        counter = 15
        limit = counter
        while cstate is False:
            for x in range(counter):
                try:
                    container = self.docker_container_get()

                    if (
                        container.attrs["State"]["Running"]
                        and container.attrs["State"]["Health"]["Status"]
                    ):
                        running = container.attrs["State"]["Running"]
                        healthy = container.attrs["State"]["Health"]["Status"]
                        logger.debug(f"container_state_running: {running}")
                        logger.debug(f"container_state_healthy: {healthy}")
                    else:
                        logger.info(f"Container is not running, restarting...")
                        self.docker_container_start()

                    if x == limit - 1:
                        # Make one last ditch attempt to start this. If this doesn't work, we
                        # will just bail on exit(1)

                        # logger.info(f'Attempting to start the container before exiting...')
                        # self.docker_container_start()

                        logger.info(f"Cannot start container. Exiting.")
                        os._exit(1)
                    if running is True and healthy == "healthy":
                        logger.info(f"Container is running and healthy.")
                        cstate = True
                        break

                    if running is True and (
                        (healthy == "starting") or (healthy == "unhealthy")
                    ):
                        if counter < 10:
                            self.docker_container_start()

                        # There could be a persistent unhealthy status
                        # and the counts against that status
                        # should result in a restart (or something).
                        #
                        # See 'x == limit' above for possible fix
                        logger.debug(f"Counter is: {counter}")
                        logger.info(f"Waiting for container status...")
                        time.sleep(5)
                    if running is False:
                        logger.info(f"Container is not running, restarting...")
                        self.docker_container_start()

                    counter = counter - 1
                except ValueError as e:
                    logger.debug(f"{e}")
                    os._exit(1)

        return True

    def docker_checkup_and_pub(self):
        try:
            if self.docker_checkup():
                if vpn().get_gw_new():
                    my_ipaddr = vpn().get_public_ip()
                else:
                    my_ipaddr = vpn().get_public_ip()
                try:
                    socket.inet_aton(my_ipaddr)
                except socket.error as e:
                    logger.debug(f"error: {e}")

                vpn_gw_name = vpn().get_gw_name(vpn().get_gw_ip())

                if mqtt_enable:
                    mqtt().mqtt_pub(vpn_gw_name, my_ipaddr)
                if mysql_enable:
                    mysql().mysql_pub(vpn_gw_name, my_ipaddr)
                if influxdb_enable:
                    influxdb_pub(vpn_gw_name, my_ipaddr)

            else:
                logger.info("docker_checkup fail")
        except ValueError as e:
            logger.debug(f"error: {e}")
            return False


class vpn:
    def __init__(self):
        pass

    def get_healthcheck(self):
        logger.debug(f"Running gluetun healthcheck against: {hostname_fqdn}")
        health = send_request(
            method="get", url=f"http://{hostname_fqdn}:" + str(gluetun_healthcheck_port)
        )
        return health

    def restart_vpn(self):
        # gluetun control server:
        #   https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/control-server.md
        # gluetun healthcheck:
        #   https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md
        #
        # If only a stop were sent, the connection would auto-heal within 6 seconds. But sending
        # a 'stopped', and immediately thereafter a 'running', we can save some precious time in
        # returning to service.
        #
        # Re: alternating between endpoint /v1/openvpn, /v1/updater, and /v1/vpn
        #   see: https://github.com/qdm12/gluetun/issues/2277
        payload = {"status": "stopped"}
        headers = {"Content-Type": "application/json"}
        send_request(
            method="put",
            url=f"http://{hostname_fqdn}:"
            + str(gluetun_control_port)
            + "/v1/vpn/status",
            data=json.dumps(payload),
            headers=headers,
        )

        payload = {"status": "running"}
        send_request(
            method="put",
            url=f"http://{hostname_fqdn}:"
            + str(gluetun_control_port)
            + "/v1/vpn/status",
            data=json.dumps(payload),
            headers=headers,
        )

    def get_public_ip(self):
        urllist_ipaddr = [
            "https://api.ivpn.net/v4/geo-lookup",
            "https://ipinfo.io/json",
            "https://ipconfig.io/json",
            "https://ifconfig.io/all.json",
            "https://ifconfig.me/all.json",
        ]
        urllist_rand = random.sample(urllist_ipaddr, len(urllist_ipaddr))

        ipaddr_public = send_request(
            method="get",
            url=urllist_rand[0],
            proxy=f"http://{hostname_fqdn}:{gluetun_proxy_port}",
        )

        logger.debug(f"Public ipaddr: {ipaddr_public}")

        return ipaddr_public

    def get_gw_name(self, ipaddr):
        # Using the servers.json file provided by gluetun, this matches
        # the gateway ip to it's associated hostname.
        try:
            with open(gluetun_servers_json) as f:
                jblob = f.read()
        except ValueError as e:
            logger.debug(f"{e}")
            os._exit(1)
        js = json.loads(jblob)
        vpn_provider = self.get_provider_name()
        if vpn_provider in js:
            servers = js[vpn_provider]["servers"]
        else:
            logger.debug(f"WARNING: servers is null")
            servers = []

        # This is an example of redefining servers with specified regions to exclude.
        #
        # excluded_regions = {'TX', 'FL', 'GA'}
        # servers = [ ep for ep in servers if ep.get('region') not in excluded_regions ]
        for ep in servers:
            for ip in ep["ips"]:
                if ip == ipaddr:
                    return ep["hostname"]

    def get_gw_ip(self):
        # This gets the ip address of the gateway we're connected to. Currently this is the
        # only means of doing this with gluetun.
        try:
            container = Docker().docker_container_get()
            container_logs = container.logs()
        except ValueError as e:
            logger.debug(f"{e}")
            os._exit(1)
        matches = []
        for line in container_logs.decode().splitlines():
            if "Connecting to" in line:
                matches.append(line)
        my_match = matches[-1]
        ipaddr = re.findall(r"[0-9]+(?:\.[0-9]+){3}", my_match)
        ipaddr = ipaddr[0]

        return ipaddr

    def randomizer(self):
        if vpn().get_healthcheck() == "OK":
            logger.debug(
                f"Healthcheck has passed. Restarting VPN via gluetun control server"
            )
            vpn().restart_vpn()
            time.sleep(3)
            logger.debug(f"VPN has been restarted. VPN IP address renewed.")
            if Docker().docker_get_ready_state():
                logger.debug(f"Ready state is OK. Proceeding to Docker checkup...")
                Docker().docker_checkup_and_pub()
        else:
            logger.debug(f"Healthcheck has NOT passed. Trying a Docker checkup...")
            Docker().docker_checkup_and_pub()

    def get_provider_name(self):
        container = Docker().docker_container_get()
        for item in container.attrs["Config"]["Env"]:
            if re.match("VPN_SERVICE_PROVIDER", item):
                provider_name = item.split("=")[1]

        return provider_name

    def shuffle_provider(self):
        # https://stackoverflow.com/questions/6648493/how-to-open-a-file-for-both-reading-and-writing
        # https://stackoverflow.com/questions/34575336/should-we-open-the-file-more-than-once-to-read-it
        logger.info(f"Shuffling provider...")
        provider_files = []
        provider_name_current = self.get_provider_name()
        env_file = os.path.join(gluetun_path, ".env")
        env_glob = os.path.join(gluetun_path, ".env.*")

        for f in glob.glob(env_glob):
            provider_files.append(f)

        provider_newfile = random.choice(provider_files)

        with open(provider_newfile, "r") as f:
            lines = f.readlines()

        new_lines = []

        for line in lines:
            if line.startswith("SERVER_CITIES"):
                key, value = line.split("=", 1)

                cities = [
                    c.strip() for c in value.strip().strip('"').split(",") if c.strip()
                ]

                if cities:
                    random.shuffle(cities)
                    shuffled_value = '"' + ", ".join(cities) + '"\n'
                    line = f"{key}={shuffled_value}"

            new_lines.append(line)

        with open(env_file, "w") as env:
            env.writelines(new_lines)

        lines = [line.strip() for line in new_lines]

        for line in lines:
            if "VPN_SERVICE_PROVIDER" in line:
                provider_name_new = line.split("=", 1)[1]

        logger.info(f"Current provider is: {provider_name_current}")
        logger.info(f"New provider is: {provider_name_new}")

        #
        # container will reload changes to .env with 'docker compose up -d'
        #  https://stackoverflow.com/questions/42149529/how-to-reload-environment-variables-in-docker-compose-container-with-minimum-dow
        #
        if provider_name_current == provider_name_new:
            logger.debug(f"VPN providers are the same. No restart neeeded.")
            pass
        else:
            logger.info(f"Provider has changed. Reloading container .env")
            Docker().docker_container_start()

        Docker().docker_checkup_and_pub()

    def get_gw_other(self):
        if mqtt_enable or mysql_enable:
            if mqtt_enable:
                mdict = mqtt().mqtt_get_messages()
            if mysql_enable:
                mdict = mysql().mysql_get_messages()
                mdict = {item["instance_name"]: item for item in mdict}

            logger.debug(f"mdict: {mdict}")

            gw_other = []

            for key, val in mdict.items():
                if key == instance_name:
                    continue
                elif val.get("vpn_gateway"):
                    gw_other.append(val["vpn_gateway"])

            logger.debug(f"Current gateway list shows: {gw_other}")
            return gw_other
        else:
            return None

    def get_gw_new(self):
        if mqtt_enable or mysql_enable:
            gw_other = self.get_gw_other()
            while True:
                gw_current = self.get_gw_name(self.get_gw_ip())
                if gw_current not in gw_other:
                    break
                else:
                    vpn().restart_vpn()
                    time.sleep(15)

            logger.debug(f"{gw_current} is not in this list: {gw_other}")
            return gw_current
        else:
            return None


class mqtt:
    def __init__(self):
        self.mqtt_broker = mqtt_broker
        self.topic_pub = mqtt_topic_pub
        self.topic_sub = mqtt_topic_sub

    def mqtt_pub(self, vpn_gateway, vpn_ipaddr):
        #
        # This takes two strings and publishes to mqtt with datetime.
        #
        logger.info(f"Publishing details to mqtt...")
        client = mqtt_client.Client(mqtt_client.CallbackAPIVersion.VERSION2)
        client.connect(self.mqtt_broker)
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        vpn_provider = vpn().get_provider_name()
        status = dict(
            datetime=now,
            vpn_provider=vpn_provider,
            vpn_gateway=vpn_gateway,
            vpn_ipaddr=vpn_ipaddr,
        )
        payload = json.dumps(status)
        client.publish(self.topic_pub, payload, retain=True)
        client.disconnect()

    def mqtt_get_messages(self):
        # Returns a dictionary containing all mqtt messages 'proxies/#' with
        # hostname as key and associated details as vals
        mdict = {}

        def on_connect(client, userdata, flags, rc, properties=None):
            client.subscribe(self.topic_sub)

        def on_message(client, userdata, msg):
            nonlocal mdict
            messages = msg.payload.decode().splitlines()
            for m in messages:
                h = msg.topic.split("/")[-1]
                m = json.loads(m)
                ddict = {h: m}
                mdict.update(ddict)
            return mdict

        client = mqtt_client.Client(mqtt_client.CallbackAPIVersion.VERSION2)
        client.connect(self.mqtt_broker)
        client.loop_start()
        client.on_connect = on_connect
        client.on_message = on_message
        time.sleep(0.5)
        client.disconnect()
        client.loop_stop()

        return mdict


class mysql:
    def __init__(self):
        self.db_config = {
            "host": config["mysql_host"],
            "user": config["mysql_user"],
            "password": config["mysql_password"],
            "database": config["mysql_database"],
        }
        self.connection = None
        self.cursor = None

    def mysql_connect(self):
        try:
            self.connection = pymysql.connect(**self.db_config)
            self.cursor = self.connection.cursor()
        except Exception as e:
            print(f"mysql: Error connecting to mysql: {e}")

    def mysql_close(self):
        if self.cursor:
            self.cursor.close()
        if self.connection:
            self.connection.close()

    def mysql_pub(self, vpn_gateway, vpn_ipaddr):
        logger.info(f"Publishing details to mysql...")
        self.mysql_connect()

        if not self.connection:
            logger.info(f"mysql: Error connecting to mysql")
            return

        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        vpn_provider = vpn().get_provider_name()

        insert_query = """
        INSERT INTO vpn_status (datetime, instance_name, vpn_provider, vpn_gateway, vpn_ipaddr)
        VALUES (%s, %s, %s, %s, %s)
        """
        status = (
            now,
            instance_name,
            vpn_provider,
            vpn_gateway,
            vpn_ipaddr,
        )

        try:
            self.cursor.execute(insert_query, status)
            self.connection.commit()
        except Exception as e:
            logger.info(f"mysql: Error inserting record: {e}")

        self.mysql_close()

    def mysql_get_messages(self):
        self.mysql_connect()

        if not self.connection:
            logger.info(f"mysql: Error connecting to mysql")
            return []

        query = """
        SELECT vpn_provider, vpn_gateway, vpn_ipaddr, instance_name FROM vpn_status
        WHERE id IN (
            SELECT MAX(id) FROM vpn_status
            GROUP BY instance_name
        )
        """

        try:
            self.cursor.execute(query)
            results = self.cursor.fetchall()
            logger.debug(f"mysql_get_messages result: {results}")
            column_names = [desc[0] for desc in self.cursor.description]
            messages = [dict(zip(column_names, row)) for row in results]
            logger.debug(f"mysql_get_messages messages: {messages}")

            return messages

        except Exception as e:
            logger.info(f"mysql: Error retrieving records: {e}")
            return json.dumps([])

        self.mysql_close()


class TimerThread(threading.Thread):
    def __init__(self, interval, function):
        threading.Thread.__init__(self)
        self.interval = interval
        self.function = function
        self.daemon = True

    def run(self):
        while True:
            logger.info(f"{str(self.function)} is sleeping for: {self.interval}")
            time.sleep(self.interval)
            self.function()
            if self.function == v.randomizer:
                self.interval = random.randint(ttl_min, ttl_max)
            if self.function == v.shuffle_provider:
                self.interval = random.randint(ttl_min, ttl_max)


if __name__ == "__main__":
    logger.info(f"Starting randomizer...")
    d = Docker()
    v = vpn()
    timer1 = TimerThread(start_delay, v.randomizer)
    timer1.start()
    timer2 = TimerThread(checkup_and_pub_interval, d.docker_checkup_and_pub)
    timer2.start()
    if shuffle_vpn_provider:
        timer3 = TimerThread(random.randint(ttl_min, ttl_max), v.shuffle_provider)
        timer3.start()

    while True:
        time.sleep(ttime_loop_sleep)
